// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'Intro',
    {
      type: 'link',
      label: 'News',
      href: 'https://www.scnx-changelog.de/blog'
    },
    {
      type: 'category',
      label: 'Changelog',
      items: [
        {
          type: 'category',
          label: 'Discord Bot',
          items: [
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/discord-bot/V3/v3.20.5',
              ]
            },
            {
              type: 'category',
              label: 'Beta',
              items: [
                'Changelog/discord-bot/Beta/V3.20.6-3',
                'Changelog/discord-bot/Beta/V3.20.6-2',
                'Changelog/discord-bot/Beta/V3.20.6-1',
              ],
            },
            {
              type: 'category',
              label: 'Not Anounced',
              items: [
                'Changelog/discord-bot/not-anounced/android-update',
                'Changelog/discord-bot/not-anounced/ads-update',
                'Changelog/discord-bot/not-anounced/New-server-32-33',
                'Changelog/discord-bot/not-anounced/image',
                'Changelog/discord-bot/not-anounced/New-server-31',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Modmail',
          items: [
            {
              type: 'category',
              label: 'Stable',
              items: [
                'Changelog/modmail/stable/Welcome',
              ],
            },
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/modmail/V3/information',
                'Changelog/modmail/V3/04-07-2025',
                'Changelog/modmail/V3/19-06-2025',
                'Changelog/modmail/V3/15-06-2025',
                'Changelog/modmail/V3/12-06-2025',
                'Changelog/modmail/V3/08-06-2025',
                'Changelog/modmail/V3/04-06-2025',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Linked Roles',
          items: [
            'Changelog/linked-roles/welcome',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        title: 'Guide',
        description: 'Here, you can find all the guides from scnx Docs.',
        slug: '/guide'
      },
      items: [
        {
          type: 'category',
          label: 'SCNX',
          link: {
            type: 'generated-index',
            title: 'SCNX',
            description: 'SCNX Guide Page, this page is about SCNX features not Bots.',
            slug: '/guide/scnx',
          },
          items: [
            {
              type: 'link',
              label: 'Add a Server to SCNX',
              href: 'https://docs.scnx.xyz/docs/setup/'
            },
            {
              type: 'link',
              label: 'Basics',
              href: 'https://docs.scnx.xyz/docs/scnx/guilds/bots/',
            },
            {
              type: 'link',
              label: 'Analytics',
              href: 'https://docs.scnx.xyz/docs/scnx/guilds/analytics/'
            },
            {
              type: 'link',
              label: 'Server Backup',
              href: 'https://docs.scnx.xyz/docs/scnx/guilds/backups/'
            },
            {
              type: 'link',
              label: 'Trusted Admins',
              href: 'https://docs.scnx.xyz/docs/scnx/guilds/trusted-admins/'
            },
            {
              type: 'link',
              label: 'dcserver.link',
              href: 'https://docs.scnx.xyz/docs/scnx/guilds/dcserver-link/'
            },
            {
              type: 'link',
              label: 'Suggest new features',
              href: 'https://feedback.scnx.xyz'
            },
          ]
        },
        {
          type: 'category',
          label: 'Custom Bot',
          link: {
            type: 'generated-index',
            title: 'Custom Bot',
            description: 'Custom bot guide page, all links are from docs.scnx.xyz and scnx.tips',
            slug: '/guide/custom-bot',
          },
          items: [
            {
              type: 'link',
              label: 'Create a custom Bot',
              href: 'https://docs.scnx.xyz/docs/custom-bot/',
            },
            {
              type: 'link',
              label: 'Modules',
              href: 'https://docs.scnx.xyz/docs/custom-bot/modules/'
            },
            {
              type: 'link',
              label: 'Custom Commands (only in German)',
              href: 'https://scnx.tips/scnx-eigene-befehle/'
            }
          ],
        },
        {
          type: 'category',
          label: 'Modmail',
          link: {
            type: 'generated-index',
            title: 'Modmail bot',
            description: 'Modmail Bot guide page, all links are from docs.scnx.xyz',
            slug: '/guide/modmail',
          },
          items: [
            {
              type: 'link',
              label: 'Create a Modmail Bot',
              href: 'https://docs.scnx.xyz/docs/modmail/',
            },
            {
              type: 'link',
              label: 'Configure Modmail',
              href: 'https://docs.scnx.xyz/docs/modmail/configuration/'
            },
            {
              type: 'link',
              label: 'Advanced features',
              href: 'https://docs.scnx.xyz/docs/modmail/advanced-features/'
            },
          ],
        },
        {
          type: 'category',
          label: 'Linked Roles',
          link: {
            type: 'generated-index',
            title: 'Linked-Roles',
            description: 'Linked-Roles Guide Page, all links are from docs.scnx.xyz',
            slug: '/guide/linked-roles',
          },
          items: [
            {
              type: 'link',
              label: 'Setup Linked-Roles',
              href: 'https://docs.scnx.xyz/docs/linked-roles/',
            },
            {
              type: 'link',
              label: 'About Linked-Roles',
              href: 'https://docs.scnx.xyz/docs/linked-roles/intro/'
            },
            {
              type: 'link',
              label: 'Manage Linked-Roles',
              href: 'https://docs.scnx.xyz/docs/linked-roles/role-management/', 
            },
            {
              type: 'link',
              label: 'How to claim Linked Role',
              href: 'https://docs.scnx.xyz/docs/linked-roles/claim-roles/',
            },
            {
              type: 'link',
              label: `Manage member's Linked-Roles`,
              href: 'https://docs.scnx.xyz/docs/linked-roles/user-management/',
            },
            {
              type: 'link',
              label: 'Troubleshooting',
              href: 'https://docs.scnx.xyz/docs/linked-roles/troubleshooting/',
            },
            {
              type: 'link',
              label: 'Linked-Roles Configuration',
              href: 'https://docs.scnx.xyz/docs/linked-roles/settings/',
            },
          ],
        },
      ],
    },
  ],
};
export default sidebars;