// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'Intro',
    {
      type: 'link',
      label: 'News',
      href: 'https://www.scnx-changelog.de/blog'
    },
    {
      type: 'category',
      label: 'Changelog',
      items: [
        {
          type: 'category',
          label: 'Discord Bot',
          items: [
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/discord-bot/V3/v3.20.5',
              ]
            },
            {
              type: 'category',
              label: 'Beta',
              items: [
                'Changelog/discord-bot/Beta/Welcome',
              ],
            },
            {
              type: 'category',
              label: 'Not Anounced',
              items: [
                'Changelog/discord-bot/not-anounced/ads-update',
                'Changelog/discord-bot/not-anounced/New-server-32-33',
                'Changelog/discord-bot/not-anounced/image',
                'Changelog/discord-bot/not-anounced/New-server-31',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Modmail',
          items: [
            {
              type: 'category',
              label: 'Stable',
              items: [
                'Changelog/modmail/stable/Welcome',
              ],
            },
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/modmail/V3/information',
                'Changelog/modmail/V3/04-07-2025',
                'Changelog/modmail/V3/19-06-2025',
                'Changelog/modmail/V3/15-06-2025',
                'Changelog/modmail/V3/12-06-2025',
                'Changelog/modmail/V3/08-06-2025',
                'Changelog/modmail/V3/04-06-2025',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Linked Roles',
          items: [
            'Changelog/linked-roles/welcome',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Guide',
      link: {
        type: 'generated-index',
        title: 'Guide',
        description: 'Here, you can find all the guides from scnx Docs.',
        slug: '/guide'
      },
      items: [
        {
          type: 'link',
          label: 'Add a Server to SCNX',
          href: 'https://docs.scnx.xyz/docs/setup/'
        },
        {
          type: 'link',
          label: 'Basics',
          href: 'https://docs.scnx.xyz/docs/scnx/guilds/bots/',
        },
        {
          type: 'link',
          label: 'Analytics',
          href: 'https://docs.scnx.xyz/docs/scnx/guilds/analytics/'
        },
        {
          type: 'link',
          label: 'Server Backup',
          href: 'https://docs.scnx.xyz/docs/scnx/guilds/backups/'
        },
        {
          type: 'link',
          label: 'Trusted Admins',
          href: 'https://docs.scnx.xyz/docs/scnx/guilds/trusted-admins/'
        },
        {
          type: 'link',
          label: 'dcserver.link',
          href: 'https://docs.scnx.xyz/docs/scnx/guilds/dcserver-link/'
        },
        {
          type: 'link',
          label: 'Suggest new features',
          href: 'https://feedback.scnx.xyz'
        },
        {
          type: 'category',
          label: 'Custom Bot',
          items: [
            {
              type: 'link',
              label: 'Create a custom Bot',
              href: 'https://docs.scnx.xyz/docs/custom-bot/',
            },
            {
              type: 'link',
              label: 'Modules',
              href: 'https://docs.scnx.xyz/docs/custom-bot/modules/'
            },
            {
              type: 'link',
              label: 'Custom Commands (only in German)',
              href: 'https://scnx.tips/scnx-eigene-befehle/'
            }
          ],
        },
        {
          type: 'category',
          label: 'Modmail',
          items: [
            {
              type: 'link',
              label: 'Create a Modmail Bot',
              href: 'https://docs.scnx.xyz/docs/modmail/',
            },
            {
              type: 'link',
              label: 'Configure Modmail',
              href: 'https://docs.scnx.xyz/docs/modmail/configuration/'
            },
            {
              type: 'link',
              label: 'Advanced features',
              href: 'https://docs.scnx.xyz/docs/modmail/advanced-features/'
            },
          ],
        },
      ],
    },
  ],
};
export default sidebars;
