// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'changelog', // Dies ist Ihre Hauptkategorie
      items: [
        'Changelog/Intro',
        {
          type: 'category',
          label: 'Discord Bot',
          items: [
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/discord-bot/V3/v3.20.5',
              ]
            },
            {
              type: 'category',
              label: 'Beta',
              items: [
                'Changelog/discord-bot/Beta/Welcome',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'modmail',
          items: [
            {
              type: 'category',
              label: 'Stable',
              items: [
                'Changelog/modmail/stable/Welcome',
              ],
            },
            {
              type: 'category',
              label: 'V3',
              items: [
                'Changelog/modmail/V3/information',
                'Changelog/modmail/V3/04-07-2025',
                'Changelog/modmail/V3/19-06-2025',
                'Changelog/modmail/V3/15-06-2025',
                'Changelog/modmail/V3/12-06-2025',
                'Changelog/modmail/V3/08-06-2025',
                'Changelog/modmail/V3/04-06-2025',
              ],
            },
          ],
        },
      ],
    },
  ],
   
};

export default sidebars;
